"""Schedule table

Revision ID: 0bdf27f5d4fa
Revises: 4daa1c6555e0
Create Date: 2021-12-26 18:47:09.956319

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users
import fastapi_users_db_sqlalchemy
from app.enums import *
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '0bdf27f5d4fa'
down_revision = '4daa1c6555e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('schedule_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('settings', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Text(), nullable=True),
    sa.Column('end_time', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('frame_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['frame_id'], ['frame.id'], name=op.f('fk_schedule_frame_id_frame')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_schedule_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule'))
    )
    op.create_index(op.f('ix_schedule_id'), 'schedule', ['id'], unique=False)
    op.create_index(op.f('ix_schedule_is_active'), 'schedule', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_is_active'), table_name='schedule')
    op.drop_index(op.f('ix_schedule_id'), table_name='schedule')
    op.drop_table('schedule')
    # ### end Alembic commands ###
