"""Social Login table

Revision ID: 3bd27789ad83
Revises: 6460051a1c53
Create Date: 2021-12-26 18:45:43.206231

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users
import fastapi_users_db_sqlalchemy
from app.enums import *
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '3bd27789ad83'
down_revision = '6460051a1c53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_login',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_token', sa.Text(), nullable=False),
    sa.Column('request_secret', sa.Text(), nullable=False),
    sa.Column('request_verifier', sa.Text(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('access_secret', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_social_login_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_social_login')),
    sa.UniqueConstraint('request_token', name=op.f('uq_social_login_request_token'))
    )
    op.create_index(op.f('ix_social_login_id'), 'social_login', ['id'], unique=False)
    op.create_index(op.f('ix_social_login_is_active'), 'social_login', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_login_is_active'), table_name='social_login')
    op.drop_index(op.f('ix_social_login_id'), table_name='social_login')
    op.drop_table('social_login')
    # ### end Alembic commands ###
