"""remove category icon

Revision ID: 3e0da3b0dc64
Revises: c3b398d6f12f
Create Date: 2022-03-27 20:05:23.126460

"""
from alembic import op
import sqlalchemy as sa
from app.enums import *
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '3e0da3b0dc64'
down_revision = 'c3b398d6f12f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'icon',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('sub_category', 'icon',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sub_category', 'icon',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('category', 'icon',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
