"""Frame Table

Revision ID: 7070844f842a
Revises: ed4f791e6773
Create Date: 2021-12-28 22:32:01.347794

"""
from alembic import op
import sqlalchemy as sa
from app.enums import *
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '7070844f842a'
down_revision = 'ed4f791e6773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frame',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('url', sqlalchemy_utils.types.url.URLType(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('schedule_type', sa.Text(), nullable=False),
    sa.Column('settings', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_frame_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_frame'))
    )
    op.create_index(op.f('ix_frame_id'), 'frame', ['id'], unique=False)
    op.create_index(op.f('ix_frame_is_active'), 'frame', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_frame_is_active'), table_name='frame')
    op.drop_index(op.f('ix_frame_id'), table_name='frame')
    op.drop_table('frame')
    # ### end Alembic commands ###
