"""Added sub category table

Revision ID: 86ef60630d3d
Revises: c760709b39b9
Create Date: 2022-02-06 17:23:36.846925

"""
from alembic import op
import sqlalchemy as sa
from app.enums import *
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '86ef60630d3d'
down_revision = 'c760709b39b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_category',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('icon', sqlalchemy_utils.types.url.URLType(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_sub_category_category_id_category')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sub_category'))
    )
    op.create_index(op.f('ix_sub_category_id'), 'sub_category', ['id'], unique=False)
    op.create_index(op.f('ix_sub_category_is_active'), 'sub_category', ['is_active'], unique=False)
    op.add_column('frame', sa.Column('sub_category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_frame_sub_category_id_sub_category'), 'frame', 'sub_category', ['sub_category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_frame_sub_category_id_sub_category'), 'frame', type_='foreignkey')
    op.drop_column('frame', 'sub_category_id')
    op.drop_index(op.f('ix_sub_category_is_active'), table_name='sub_category')
    op.drop_index(op.f('ix_sub_category_id'), table_name='sub_category')
    op.drop_table('sub_category')
    # ### end Alembic commands ###
