"""add category slug

Revision ID: c3b398d6f12f
Revises: 86ef60630d3d
Create Date: 2022-03-12 16:50:15.161255

"""
from alembic import op
import sqlalchemy as sa
from app.enums import *
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'c3b398d6f12f'
down_revision = '86ef60630d3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tag')),
    sa.UniqueConstraint('name', name=op.f('uq_tag_name'))
    )
    op.create_index(op.f('ix_tag_id'), 'tag', ['id'], unique=False)
    op.create_index(op.f('ix_tag_is_active'), 'tag', ['is_active'], unique=False)
    op.add_column('category', sa.Column('slug', sa.String(length=255), nullable=True))
    op.add_column('sub_category', sa.Column('slug', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sub_category', 'slug')
    op.drop_column('category', 'slug')
    op.drop_index(op.f('ix_tag_is_active'), table_name='tag')
    op.drop_index(op.f('ix_tag_id'), table_name='tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
