"""Added category table

Revision ID: c760709b39b9
Revises: ae52bca8aeac
Create Date: 2022-02-06 17:22:50.332598

"""
from alembic import op
import sqlalchemy as sa
from app.enums import *
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'c760709b39b9'
down_revision = 'ae52bca8aeac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('icon', sqlalchemy_utils.types.url.URLType(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category'))
    )
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.create_index(op.f('ix_category_is_active'), 'category', ['is_active'], unique=False)
    op.add_column('frame', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_frame_category_id_category'), 'frame', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_frame_category_id_category'), 'frame', type_='foreignkey')
    op.drop_column('frame', 'category_id')
    op.drop_index(op.f('ix_category_is_active'), table_name='category')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
