"""Purchase Table

Revision ID: ed4f791e6773
Revises: 330e2de920af
Create Date: 2021-12-28 22:31:45.714111

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users
import fastapi_users_db_sqlalchemy
from app.enums import *
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'ed4f791e6773'
down_revision = '330e2de920af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=320), nullable=False),
    sa.Column('remaining_custom_frames', sa.Integer(), nullable=False),
    sa.Column('remaining_frame_usage', sa.Integer(), nullable=False),
    sa.Column('remaining_active_schedules', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Text(), nullable=True),
    sa.Column('end_time', sa.Text(), nullable=True),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=15), nullable=False),
    sa.Column('payment_id', sa.String(length=320), nullable=False),
    sa.Column('payment_status', sa.String(length=320), nullable=True),
    sa.Column('payment_method', sa.String(length=320), nullable=True),
    sa.Column('billing_address', sa.Text(), nullable=True),
    sa.Column('shipping_address', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], name=op.f('fk_purchase_plan_id_plan')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_purchase_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase')),
    sa.UniqueConstraint('payment_id', name=op.f('uq_purchase_payment_id'))
    )
    op.create_index(op.f('ix_purchase_id'), 'purchase', ['id'], unique=False)
    op.create_index(op.f('ix_purchase_is_active'), 'purchase', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_is_active'), table_name='purchase')
    op.drop_index(op.f('ix_purchase_id'), table_name='purchase')
    op.drop_table('purchase')
    # ### end Alembic commands ###
