"""SocialLogin table

Revision ID: ee2fd473d550
Revises: 86f6aa2bfb18
Create Date: 2021-12-25 22:05:51.168528

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users
import fastapi_users_db_sqlalchemy
from app.enums import *
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'ee2fd473d550'
down_revision = '86f6aa2bfb18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_login',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_token', sa.Text(), nullable=False),
    sa.Column('request_secret', sa.Text(), nullable=False),
    sa.Column('request_verifier', sa.Text(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('access_secret', sa.Text(), nullable=True),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_social_login_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_social_login'))
    )
    op.create_index(op.f('ix_social_login_id'), 'social_login', ['id'], unique=False)
    op.create_index(op.f('ix_social_login_is_active'), 'social_login', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_login_is_active'), table_name='social_login')
    op.drop_index(op.f('ix_social_login_id'), table_name='social_login')
    op.drop_table('social_login')
    # ### end Alembic commands ###
