"""Plan table

Revision ID: f39ee9e6e355
Revises: ee2fd473d550
Create Date: 2021-12-25 22:07:14.570550

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users
import fastapi_users_db_sqlalchemy
from app.enums import *
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'f39ee9e6e355'
down_revision = 'ee2fd473d550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('max_custom_frames', sa.Integer(), nullable=False),
    sa.Column('max_frame_usage', sa.Integer(), nullable=False),
    sa.Column('max_active_schedules', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan'))
    )
    op.create_index(op.f('ix_plan_id'), 'plan', ['id'], unique=False)
    op.create_index(op.f('ix_plan_is_active'), 'plan', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plan_is_active'), table_name='plan')
    op.drop_index(op.f('ix_plan_id'), table_name='plan')
    op.drop_table('plan')
    # ### end Alembic commands ###
